part of 'package:gauge/app/core/theme/theme.dart';

ThemeData get darkTheme => ThemeData.dark().copyWith(
      brightness: Brightness.dark,
      scaffoldBackgroundColor: Palette.gray[900],
      cardColor: Palette.gray[800],
      dividerColor: Palette.gray[700],
      appBarTheme: AppBarTheme(
        backgroundColor: Palette.gray[800],
        elevation: 0,
      ),
      // visualDensity: ,
      // primaryColor: ,
      // primaryColorLight:,
      // primaryColorDark:,
      // accentColor:,
      // accentColorBrightness:,
      // canvasColor:,
      // shadowColor:,
      // bottomAppBarColor:,
      // focusColor:,
      // hoverColor:,
      // highlightColor:,
      // splashColor:,
      // splashFactory:,
      // selectedRowColor:,
      // unselectedWidgetColor:,
      // disabledColor:,
      // buttonTheme:,
      // toggleButtonsTheme:,
      // buttonColor:,
      // secondaryHeaderColor:,
      // textSelectionColor:,
      // cursorColor:,
      // textSelectionHandleColor,
      // backgroundColor:,
      // dialogBackgroundColor:,
      // indicatorColor:,
      // hintColor:,
      // errorColor:,
      // toggleableActiveColor:,
      // textTheme:,
      // primaryTextTheme:,
      // accentTextTheme:,
      // inputDecorationTheme:,
      // iconTheme:,
      // primaryIconTheme:,
      // accentIconTheme:,
      // sliderTheme:,
      // tabBarTheme:,
      // tooltipTheme:,
      // chipTheme:,
      // platform:,
      // materialTapTargetSize:,
      // applyElevationOverlayColor:,
      // pageTransitionsTheme:,
      // scrollbarTheme:,
      // bottomAppBarTheme:,
      colorScheme: ColorScheme.dark(
        primary: Palette.primary[500]!,
        primaryContainer: Palette.primary[500]!.withOpacity(0.15),
        onPrimary: Colors.white,
        error: Palette.red?[500] ?? Colors.red,
        errorContainer: (Palette.red?[500] ?? Colors.red).withOpacity(0.15),
        onError: Colors.white,
        surfaceContainerHighest: Palette.gray[800]!,
        onSurfaceVariant: Palette.gray[400]!,
      ),
      // dialogTheme:,
      // floatingActionButtonTheme:,
      // navigationRailTheme:,
      // typography:,
      // cupertinoOverrideTheme:,
      // snackBarTheme:,
      // bottomSheetTheme:,
      // popupMenuTheme:,
      // bannerTheme:,
      cardTheme: CardThemeData(
        color: Palette.gray[800],
        elevation: 0,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(20),
          side: BorderSide(color: Palette.gray[700]!, width: 1),
        ),
      ),
      dividerTheme: DividerThemeData(
        color: Palette.gray[700],
        space: 24,
        thickness: 1,
      ),
      // buttonBarTheme:,
      // bottomNavigationBarTheme:,
      // timePickerTheme:,
      // textButtonTheme:,
      elevatedButtonTheme: const ElevatedButtonThemeData(),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          foregroundColor: Palette.gray[200],
          side: BorderSide(color: Palette.gray[600]!),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
        ),
      ),
      filledButtonTheme: FilledButtonThemeData(
        style: FilledButton.styleFrom(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
        ),
      ),
      // textSelectionTheme:,
      // dataTableTheme:,
      // checkboxTheme: CheckboxThemeData(
      // mouseCursor:,
      // fillColor: ,
      // checkColor:,
      // overlayColor:,
      // splashRadius:,
      // materialTapTargetSize:,
      // visualDensity:,
      // shape:,
      // side:,
      // ),
      // radioTheme:,
      // switchTheme:,
      // progressIndicatorTheme:,
      // fixTextFieldOutlineLabel:,
      // useTextSelectionTheme:,
    );